function PlotDisp(dispersion_ratio, h_over_lambda, nmodes, Data)
    % reshape: rows = modes, cols = different meshes
    % From a 1d matrix obtain a 2d matrix in which each column rapresents a
    % different mode
    R = reshape(dispersion_ratio, nmodes, []);
    H = reshape(h_over_lambda,  nmodes, []);

    figure; grid on; hold on;

    fs = 25;   % SAME font size as other figures
    
    % Iterate for each mode
    for m = 1:nmodes
        [Hs, idx] = sort(H(m,:));
        plot(Hs, R(m,idx), '-o', ...
             'LineWidth', 1.8, ...
             'MarkerSize', 6);
    end
    
    set(gca,'XScale','log')
    set(gca,'YScale','log')
    
    xlabel('$h/\lambda$', ...
           'Interpreter','latex', ...
           'FontName','Times New Roman', ...
           'FontSize',fs);
    
    ylabel('$k_h/k$', ...
           'Interpreter','latex', ...
           'FontName','Times New Roman', ...
           'FontSize',fs);
    
    title('Dispersion curve', ...
          'Interpreter','latex', ...
          'FontName','Times New Roman', ...
          'FontSize',fs);
    
    legend(arrayfun(@(m) sprintf('$\\mathrm{mode}\\ %d$', m), ...
                    1:nmodes, 'UniformOutput', false), ...
           'Interpreter','latex', ...
           'Location','best', ...
           'FontName','Times New Roman', ...
           'FontSize',fs);

    
    if Data.save_sol_images
    exportgraphics(gcf, fullfile('Plots', 'Dispersionplot.pdf'), ...
                   'ContentType','vector');
    end

end